language: ruby
rvm:
  - "2.1.1"

## multijobs: can be useful if we have hundreds of tests...
# env:
# - CARD_SET=services
# - CARD_SET=users
# - CARD_SET=search

script:
  - bundle exec rake db:test:purge
  - bundle exec rake db:test:prepare
  - bundle exec rake test
  - bundle exec rake cucumber:all

before_script:
  # Needed for selenium browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  # Use postgres
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database rsnap_test;' -U postgres
  # Install dependences
  #- travis_retry bundle install --verbose

env:
  global:
    # Amazon AWS information
    - S3_BUCKET_NAME=snap-school-test
    - secure: "Rz+yzgqyyQMR9qwc6AJlmQMG9k1Ma7YHwWdyx2QtAo+a5fFTtCuaZ1EsttE6nIiwkQ21QqeM0k5FJJF+2vkNxdUssHIxOeFPhpioyKkYd+vbZoeWxLkt5oIiNGc9X9vf2QP0SxOvjzFeUWhk2uC6KqVVmdi+JstrH0DkxaE5arA="
    - secure: "gEmW5o72JyePiRLFKEd7QiF0RKltyF5hgedQ85biLJ6cHNx/UWh8UWlfjhXIAuty0oJQq53h+dniEOyAPmpJc2eTZAI7nnpQcVBQum75tMoZmfXSk0IiMRFXTFeorqnn46cfk83WoPlMm7PRsJxx64ug/DfMbbFt2NB+RZ3d8Wo="
    # Rails information
    - RAILS_SECRET_KEY=3f249c7ca31b4d18fa2d8d7dfa41e23a5f04d563c49ae61db098937f470310a8efb80bfd116c2198b0a6c62647640d126b20ba63ab6e539701ce85f16ecd18e3
    - RACK_ENV=test
    - PORT=3000
    - DEVISE_SECRET_KEY=eafc262c326966ea1bc41c4da056d651ca0ca9e2056574c0445b1cbb44732c81ffeed7d4d215185ef25dfcaed4e5de2afc30ed85bf1fbedc47491eeaea572ebb
    # Code testing information
    - CODECLIMATE_REPO_TOKEN=5f6d9eeb5d6f7c0077103ce9c3cac3d1caa678aadf1203bc55a14fc97f5f6e71

